### PR TITLE
New Sampling Method

### PR DESCRIPTION
**Pull request by genericusername1199**
new implementation of sampling method and associated changes to bootstrapping.

Apologies that it so messy! I will clean it up a bit. Seems stable on my machine but I'm around to fix it if/when it breaks. I forced each set to be the same size in the end because it looked like maybe that's what the rest of the method expected so actually it slightly over samples each time.

### CODE REVIEW

**Comment by HannahVMeyer** [comment]
I added a [file](https://github.com/HannahVMeyer/limmbo/blob/new-sampling-method/performance/Evaluate_sampling.py) to where I wanted to compare the performance of the random sampling compared to the set coverage
However, for P=100, S=10, minCooccurrence=3, multiple_set_covers_all fails with the following error:
image

I added a counter to your function to check where this occurs, and it is at 539, where 
used_subsets[539] = array([4852, 4853, 4854, 4855, 4856, 4857, 4858, 4859, 4860]). However, len(number_to_tuple) = 4851, so number_to_tuple[4852] fails with index error.

**Comment by odysseusulysses** [comment]
My git isn't happy about something and I can't push anything but It looks like the method in the performance testing file and the method in utils.py are very slightly different.

The line directly under the comment     
'#Create a dictionary to store mappings between tuples and traits. Should be a function really'

in utils.py it is

'for i in range(0, number_of_traits):' 

and in Evaluate_sampling.py

'for i in range(1, number_of_traits):'

If you change back to the utils.py version it should work

**Comment by HannahVMeyer** [comment]
Sorry for the mess up when copying the file - works all fine now!

I have done some testing of the set coverage method to the random sampling method - comparing the number of draws needed to achieve coverage, the time needed for constructing the sampling_array and the coverage on tuple/trait level. For each method and different trait sizes, I ran 50 sampling simulations. Results are visualised [here](https://github.com/HannahVMeyer/limmbo/blob/new-sampling-method/performance/sampling.pdf).

First, comparison of the coverage: Here I just plot the average counts observed per trait index across the 50 simulations. Noticeably, in the set cover, the traits with higher indices are sampled more (color bar is normalised to max number of sampling steps per trait size).

Second, I compare the number of draws needed (rows of sampling array) to achieve coverage and the time it takes to construct the sampling arrays. For lower trait numbers, the random sampling seems to do better than the set coverage and vice versa.

**Comment by odysseusulysses** [comment]
Think I fixed it without breaking everything else now. Attached is the new performance .
[sampling.pdf](https://github.com/HannahVMeyer/limmbo/files/2225007/sampling.pdf)

**Review by HannahVMeyer — APPROVED** [review]

**Pull request merged**
